services:
  data_ingestion:
    build: .
    container_name: data-ingestion
    depends_on:
      db:
        condition: service_healthy  

  db:
    image: postgres:18
    container_name: pgdatabase
    ports:
      - "5432:5432"
    volumes:
      - ~/ny_taxi_postgres_2_data:/var/lib/postgresql
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=ny_taxi
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
  
  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=root
    volumes:
      - "pgadmin_data:/var/lib/pgadmin"
    ports:
      - "8085:80"
    depends_on:
      db:
        condition: service_healthy
volumes:
  pgadmin_data: {}