[project]
name = "data-pipeline"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Gabriel Ribeiro Alves", email = "111773987+GaRa2901@users.noreply.github.com" }
]
requires-python = ">=3.13"
dependencies = [
    "pandas>=3.0.5",
    "pyarrow>=25.0.1",
]

[tool.uv] 
package=false  # this tells uv to treat the project as standalone application or data pipeline rather than a redistributable Python library.


[project.scripts]
data-pipeline = "data_pipeline:main"

[build-system]
requires = ["uv_build>=0.12.5,<0.13.0"]
build-backend = "uv_build"

# installed through uv add --dev pgcli -> the --dev argument indicates uv to create a group of dependencies named dev apart from the main dependencies.
# The reason for it is that I would only want to use this dependencies while I'm in development.
[dependency-groups]
dev = [
    "jupyter>=1.1.1",
    "pgcli>=4.5.0",
]
